# Assignment 3 - Data Analysis

## Data set Introduction - Persons living in acceptable housing

I found this data set via Statistics Canada from the period 2020-2021.

The reason I chose this is to get a deeper understanding on people living in acceptable housing versus not living in acceptable housing, based on factors such as location, housing tenure, and year. The dataset is mostly metadata and government referencing, but with the columns left over after dropping unimportant columns we can still uncover patterns with the deciding columns.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import your helper module
import sys
sys.path.insert(0, '..')
from src.helpers import *

In [2]:
import pandas as pd
df = pd.read_csv('../data/housing2022.csv')

# Initial Exploration

In [3]:
df.shape

(364, 17)

### `df.shape`
This just gives us how many rows (364) and how many columns (17) the data set contains. This information tells us that our dataset is large enough for in depth analysis and we can now explore more deeply to see if it is suitable.

In [4]:
df.head()

,REF_DATE,GEO,DGUID,Tenure including first-time homebuyer and social and affordable housing status,Acceptable housing,Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2021,Canada (excluding territories),2021A000011124,"Total, by tenure",Does not live in acceptable housing,Percentage of persons,Percent,239,units,0,v1544264166,1.1.1.1,29.0,NaN,NaN,NaN,1
1,2022,Canada (excluding territories),2021A000011124,"Total, by tenure",Does not live in acceptable housing,Percentage of persons,Percent,239,units,0,v1544264166,1.1.1.1,31.0,NaN,NaN,NaN,1
2,2021,Canada (excluding territories),2021A000011124,"Total, by tenure",Lives in acceptable housing,Percentage of persons,Percent,239,units,0,v1544264172,1.1.11.1,71.0,NaN,NaN,NaN,1
3,2022,Canada (excluding territories),2021A000011124,"Total, by tenure",Lives in acceptable housing,Percentage of persons,Percent,239,units,0,v1544264172,1.1.11.1,69.0,NaN,NaN,NaN,1
4,2021,Canada (excluding territories),2021A000011124,Owner household,Does not live in acceptable housing,Percentage of persons,Percent,239,units,0,v1544264232,1.2.1.1,22.0,NaN,NaN,NaN,1

### `df.head()`

When we run `df.head()` we pulling the first 5 rows from our dataset to get a general overview of the dataset. \
We can see that some columns are of importance and some are merely unimportant for probably government documentation or reference. The columns Statistics, UOM, DGUID, VECTOR, UOM_ID, Scalar_factor, Scalar_id, coordinate, status, symbol, terminated, and decimals, from first glance do not provide any valuable info.

The purpose and decision to choose this data set is to see similarities on percent of acceptable housing conditions pertaining to location(geo), owner/renter(tenure), and year (ref_date).

The columns we will use from this first overview will be REF_DATE : the date when the data was collected, GEO: The location of the data, Tenure including first-time homebuyer and social and affordable housing status: If the person owns or rents the housing, Acceptable Housing: does or does not live in acceptable housing, and Value: percent of people per location that lives in or doesn't live in acceptable housing.

Even though our columns will be reduced to these core columns, I am confident that we can discover patterns within these chosen columns. When we run `df.value_counts('GEO')` we see all the locations and that there are 28 distinct values pertaining to the location, with that we can compare different locations with unacceptable housing or not.

In [5]:
df.value_counts('GEO')

GEO
Alberta                           28
Atlantic Region                   28
British Columbia                  28
Canada (excluding territories)    28
Manitoba                          28
New Brunswick                     28
Newfoundland and Labrador         28
Nova Scotia                       28
Ontario                           28
Prairies Region                   28
Prince Edward Island              28
Quebec                            28
Saskatchewan                      28
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364 entries, 0 to 363
Data columns (total 17 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   REF_DATE                                                                        364 non-null    int64
 1   GEO                                                                             364 non-null    object
 2   DGUID                                                                           364 non-null    object
 3   Tenure including first-time homebuyer and social and affordable housing status  364 non-null    object
 4   Acceptable housing                                                              364 non-null    object
 5   Statistics                                                                      364 non-null    object
 6   UOM                                                                             364 non-null    object
 7   UOM_ID                                                                          364 non-null    int64
 8   SCALAR_FACTOR                                                                   364 non-null    object
 9   SCALAR_ID                                                                       364 non-null    int64
 10  VECTOR                                                                          364 non-null    object
 11  COORDINATE                                                                      364 non-null    object
 12  VALUE                                                                           364 non-null    float64
 13  STATUS                                                                          0 non-null      float64
 14  SYMBOL                                                                          0 non-null      float64
 15  TERMINATED                                                                      0 non-null      float64
 16  DECIMALS                                                                        364 non-null    int64
dtypes: float64(4), int64(4), object(9)
memory usage: 48.5+ KB

### `df.info()` 
When we run `df.info` we get a summary of our dataframes structure and metadata. We get a quick run down if there are any missing data in terms of null or non-null. We get each columns data type. We also get how many columns and rows are in the dataset. 

17 columns, 364 rows

STATUS, SYMBOL, TERMINATED are all 0 non-null, more evidence to why we would drop these columns. 

3 different data types: float64 which is numbers with decimals, int64 which is integers, and object which is a string, text data.

In [7]:
df.describe()

,REF_DATE,UOM_ID,SCALAR_ID,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
count,364.000000,364.0,364.0,364.000000,0.0,0.0,0.0,364.0
mean,2021.500000,239.0,0.0,50.000000,NaN,NaN,NaN,1.0
std,0.500688,0.0,0.0,22.118484,NaN,NaN,NaN,0.0
min,2021.000000,239.0,0.0,10.900000,NaN,NaN,NaN,1.0
25%,2021.000000,239.0,0.0,30.000000,NaN,NaN,NaN,1.0
50%,2021.500000,239.0,0.0,50.000000,NaN,NaN,NaN,1.0
75%,2022.000000,239.0,0.0,70.000000,NaN,NaN,NaN,1.0
max,2022.000000,239.0,0.0,89.100000,NaN,NaN,NaN,1.0

### `df.describe()`
When we run `df.describe()` we are only running the intergers and float data types, and honestly the only one worth looking at is `VALUE` as this number represents our predicting column. All other columns are ones I plan to drop, besides the `REF_DATE` but running `describe()` on a date has no significance, other than our dataset spans from 2021-2022.

`VALUE` percentage of people in acceptable or unacceptable housing 

- min of 10.9 %
- max of 89.1%
- avg of 50%
- The wide range in values suggests that housing conditions vary significantly depending on location and tenure.
- The standard deviation (22.1) indicates a relatively high level of variability in housing conditions across the dataset.
- Columns such as `UOM_ID`, `SCALAR_ID`, and `DECIMALS` have constant values, further evidence to drop the columns later.

# Analytical Questions

1. Do renters experience a higher percentage of unacceptable housing compared to homeowners?

2. Which provinces have the highest and lowest percentages of people living in unacceptable housing?

3. How do housing conditions differ between first-time homebuyers and non-first-time homeowners?

4. How have housing conditions changed between 2021 and 2022 across different regions?

### Observations

1. The dataset contains 364 rows and 17 columns, indicating a moderately sized dataset suitable for analysis.

2. The data includes information for two years, 2021 and 2022, which allows for basic comparison over time.

3. The dataset includes multiple categories of housing tenure, such as owners, renters, and first-time homebuyers.

4. The dataset will be reduced in columns, but there is many comparisons to make from how much information is in each column.

5. The values are represented as percentages, making it easier to compare housing conditions across different groups.

6. Several columns (such as DGUID, VECTOR, and COORDINATE) appear to be metadata and do not contribute meaningful information for analysis.

# Cleaning the Dataset

### Clean column names
I standarized column names to ensure consistency and make them easier to read and work with during analysis.

### Cleaning decisions

I removed metadata columns such as DGUID, VECTOR, COORDINATE, STATUS, SYMBOL, TERMINATED, DECIMALS,  UOM, UOM_ID, SCALAR_FACTOR because they are reference fields used for documentation and do not help for further analysis.

I chose to keep REF_DATE, GEO, Tenure including first-time homebuyer and social and affordable housing status, affordable housing status, Acceptable housing, and VALUE, because this information will be compared with one another to predict if a housing is acceptable or not.

I will also update column names for readability.